/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lwu7' at '12/21/16 1:51 PM' with Gradle 2.12
 *
 * @author lwu7, @date 12/21/16 1:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
